name: Fetch AQW Data
permissions: 
  contents: write
on:
  schedule:
    - cron: "0 0 * * *"   # run once a day at midnight UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch AQW data (no headers)
        run: |
          mkdir -p data
          curl -sSL \
            -H "cookie: cf_clearance=2eUT3WzLBgNQMO0XG0eCORGHQbojiyZxFrLoYrYr1QM-1745165636-1.2.1.1-SqkR0hoZ3oV.jW9pDWwv5zWTIbztyB8o7Z5g8DnBx.2hPad3.orqZtACxQ8Yn4Evbv3B1kuvCHy8S5em0W2QPd_0KfvH3fdL.vsVkIAegzeN4Lc7Ods_kAQtIznoDaYG_wPHwHQPQ0Bgp1b0yfiiTtqaHRjHA9PGHwyFC3QK4X.Z0eWXuZ2HI5fUtjGY.saNPIaH1aTnNO40agWTVUdANI1Q.J6YJ5w59OQEfR0.TrZnBnu8XqUktRPUDXKBUHQA9EcMs4tydUtbntA094_Dz4WCwfSxnUE9aVUksHoLpUIIHJ0yPkBGW0Qu.vg6aCmOem.qLQcv6vKzATqdI6OQrHUtqvHNgrRWyRn5OuQtDRYFxNKYhALRfvos7j8Obzbf; __RequestVerificationToken=-qwjT5scHMsL0yVrHlM6Re6VKarupJTC2gVOYYbGX3V70aptJwc4BEpnCBiitMnt7K8bKEqjdGZlZh0ODOvxbxe48xyBInC9EGTOdYDIayU1; ASP.NET_SessionId=mhf34i4lpoqebi4dbaufdug4; snickerdoodleAQW=KaC3QIXDo0O65WJzw28vpfjgNsKs3kexQs8ddefp; __cflb=04dTocX5CGvapQX63C16eHjNv6zbskMZKp3LGbU3wK" \
            -H "user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0" \
            "https://account.aq.com/AQW/AweItemData?name=" \
            -o data/ioda_count.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Convert JSON to CSV
        run: |
          python scripts/csv-convert.py

      - name: Commit and push if changed
        
        run: |
          git config --global user.name "Shell1010"
          git config --global user.email "Shell1010@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add data/ioda_count.json data/ioda_count.csv
            git commit -m "Update AQW data ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          else
            echo "No changes to commit"
          fi

